# Site settings 配置站点
title: xiaOp的博客
email: pyqiverson@gmail.com
description: >
  分享写代码，听音乐，看电影的心得
keywords:
  - coding
  - 编程
  - javascript
  - xiaoiver
  - xiaop
chrome-tab-theme-color: "#4acaa8"
baseurl: ""
url: "https://xiaoiver.github.io"
github_username: xiaoiver

# Responsive image
responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 480
      quality: 80
    - width: 800
    - width: 1400
      quality: 90
  output_path_format: assets/img/resized/%{width}/%{basename}
  auto_rotate: true

# Navigation links
nav:
  home: '/'
  tags: '/tags.html'

# Author 配置博主信息
author: '潘宇琪'
nickname: 'xiaOp'
bio: '分享写代码，听音乐，看电影的心得'
avatar: '/assets/img/avatar.jpg'

# Search
search: true

# Night mode
nightMode: false

# Comments
disqus: false
disqus_url: 'https://liaokeyu.disqus.com/embed.js'

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'douban', 'twitter']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站url: weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  github: '//github.com/xiaoiver'
  douban: '//www.douban.com/people/150275082/'
  zhihu: '//www.zhihu.com/people/pan-yu-qi-20/activities'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.babel.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# PWA
pwa:
  sw_filename: service-worker.js
  dest_js_directory: assets/js
  cache_name: xiaop-blog-cache
  precache_channel_name: sw-precache
  precache_recent_posts_num: 3
  precache_glob_directory: /
  precache_glob_patterns:
    - "assets/{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
  precache_glob_ignores:
    - sw-register.js
    - "fonts/**/*"
  runtime_cache:
    - route: /assets\/(img|icons)/
      strategy: cacheFirst
    - route: /^https?:\/\/cdn.staticfile.org/
      strategy: staleWhileRevalidate
    - route: /^https?:\/\/at.alicdn.com/
      strategy: staleWhileRevalidate

RSS: false
